### 학습목표
#### linalg 서브모듈 함수 활용여 선형대수 연산하기

In [1]:
import numpy as np

#### np.linalg.inv
 - 역행렬을 구할 때 사용
 - 모든 차원의 값이 같아야 함

In [2]:
x = np.random.rand(3, 3, 3)
print(x)

[[[0.52010957 0.63745057 0.6445105 ]
  [0.6700035  0.44769053 0.25047975]
  [0.67706473 0.55039553 0.90461554]]

 [[0.18033419 0.67401046 0.24984957]
  [0.42252524 0.71841113 0.94807626]
  [0.38925436 0.7816097  0.61420458]]

 [[0.74201074 0.3117918  0.01214225]
  [0.73625348 0.15332571 0.06090329]
  [0.31944537 0.40774861 0.65183914]]]


In [4]:
np.matmul(x, np.linalg.inv(x))

array([[[ 1.00000000e+00, -7.94699065e-17, -1.84732219e-16],
        [-1.12073546e-16,  1.00000000e+00, -6.69565132e-17],
        [-2.24857327e-16,  6.25678163e-17,  1.00000000e+00]],

       [[ 1.00000000e+00, -8.61167453e-17,  3.22150973e-16],
        [ 9.26926300e-17,  1.00000000e+00, -5.08793275e-17],
        [-5.14266149e-17, -3.09931017e-16,  1.00000000e+00]],

       [[ 1.00000000e+00,  1.36725231e-16,  2.78998825e-18],
        [ 7.04779946e-17,  1.00000000e+00, -1.11367303e-17],
        [ 1.26599795e-16,  2.56130837e-17,  1.00000000e+00]]])

행렬 곱 사용: @

역행렬을 곱했으니 단위행렬이 된 것을 확인할 수 있음

In [5]:
x @ np.linalg.inv(x)

array([[[ 1.00000000e+00, -7.94699065e-17, -1.84732219e-16],
        [-1.12073546e-16,  1.00000000e+00, -6.69565132e-17],
        [-2.24857327e-16,  6.25678163e-17,  1.00000000e+00]],

       [[ 1.00000000e+00, -8.61167453e-17,  3.22150973e-16],
        [ 9.26926300e-17,  1.00000000e+00, -5.08793275e-17],
        [-5.14266149e-17, -3.09931017e-16,  1.00000000e+00]],

       [[ 1.00000000e+00,  1.36725231e-16,  2.78998825e-18],
        [ 7.04779946e-17,  1.00000000e+00, -1.11367303e-17],
        [ 1.26599795e-16,  2.56130837e-17,  1.00000000e+00]]])

#### np.linalg.solve
 - Ax = B 형태의 선형대수식 솔루션을 제공
 - 예제) 호랑이와 홍합의 합 : 25 호랑이 다리와 홍합 다리의 합은 64
   - x + y = 25
   - 2x + 4y = 64
   
 $$\begin{pmatrix} 1 & 1 \\ 2 & 4 \end{pmatrix}\begin{pmatrix} x \\ y \end{pmatrix}= \begin{pmatrix} 25 \\ 64 \end{pmatrix}$$


In [6]:
A = np.array([[1, 1], [2, 4]])
B = np.array([25, 64])

In [7]:
x = np.linalg.solve(A, B)
print(x)

[18.  7.]


In [8]:
np.allclose(A@x, B)

True