### 학습목표
#### 브로드캐스팅의 이해

In [1]:
import numpy as np

#### 브로드캐스팅
  - Shape이 같은 두 ndarray에 대한 연산은 각 원소별로 진행
  - 연산되는 두 ndarray가 다른 Shape을 갖는 경우 브로드 캐스팅(Shape을 맞춤) 후 진행
    
    


#### 브로드캐스팅 Rule
 - [공식문서](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#general-broadcasting-rules)
 - 뒷 차원에서 부터 비교하여 Shape이 같거나, 차원 중 값이 1인 것이 존재하면 가능

![브로드캐스팅 예](https://www.tutorialspoint.com/numpy/images/array.jpg)
    - 출처: https://www.tutorialspoint.com/numpy/images/array.jpg 

* Shape이 같은 경우의 연산

In [2]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.93607933 0.94564331 0.91425038 0.1500726  0.30482186]
 [0.39863226 0.48222227 0.89521996 0.93398231 0.47742505]
 [0.05213551 0.38085575 0.39570368 0.84639674 0.46812023]]


In [3]:
x * y

array([[ 0.        ,  0.94564331,  1.82850075,  0.45021781,  1.21928745],
       [ 1.99316128,  2.89333362,  6.26653974,  7.47185844,  4.29682545],
       [ 0.52135505,  4.18941323,  4.74844417, 11.00315764,  6.55368325]])

* Scalar(상수)와의 연산

In [4]:
x % 2 == 0

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

* Shape이 다른 경우 연산

In [6]:
a = np.arange(12).reshape(4, 3)
b = np.arange(100, 103)
c = np.arange(1000, 1004)
d = b.reshape(1, 3)

In [9]:
print(a)
print(b)
print(c)
print(d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[100 101 102]
[1000 1001 1002 1003]
[[100 101 102]]


In [10]:
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

(4, 3)
(3,)
(4,)
(1, 3)


In [11]:
a + b

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

뒷 차원부터 비교하게 됨.

a는 (4,3)이고 c는 (4,)이기 때문에 3과 4를 비교해서 다르기 때문에 broadcasting 불가능.

In [12]:
a + c

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

d는 b(1차원 벡터)를 행렬(1,3)로 만든것임.

a는 (4,3)이고 d는 (1,3)이기 때문에 뒷 차원부터 비교했을 때 3으로 같고 앞에 1이기 때문에 broadcasting 가능.

In [13]:
a + d

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])