### 학습목표
#### numpy에서 자주 사용되는 함수들을 사용해보기

In [1]:
import numpy as np

#### numpy documentation
 - [numpy 공식 문서 링크](https://www.numpy.org/devdocs/reference/)
 - numpy에서 제공되는 함수등에 대한 문서

In [2]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.26852377 0.03421536 0.19640268 0.19258763 0.60889831]
 [0.8528341  0.73470471 0.37159011 0.99058906 0.09012446]
 [0.47413979 0.69764446 0.22532868 0.35951592 0.38911209]]


#### 연산 함수
 - add, substract, multiply, divide

In [3]:
np.add(x, y)

array([[ 0.26852377,  1.03421536,  2.19640268,  3.19258763,  4.60889831],
       [ 5.8528341 ,  6.73470471,  7.37159011,  8.99058906,  9.09012446],
       [10.47413979, 11.69764446, 12.22532868, 13.35951592, 14.38911209]])

In [4]:
np.divide(x, y)

array([[ 0.        , 29.22663759, 10.18316025, 15.5773245 ,  6.56924145],
       [ 5.86280499,  8.16654629, 18.83796089,  8.0760028 , 99.86189941],
       [21.09082644, 15.76734367, 53.25553826, 36.15973417, 35.97934941]])

In [5]:
x + y

array([[ 0.26852377,  1.03421536,  2.19640268,  3.19258763,  4.60889831],
       [ 5.8528341 ,  6.73470471,  7.37159011,  8.99058906,  9.09012446],
       [10.47413979, 11.69764446, 12.22532868, 13.35951592, 14.38911209]])

In [6]:
x / y

array([[ 0.        , 29.22663759, 10.18316025, 15.5773245 ,  6.56924145],
       [ 5.86280499,  8.16654629, 18.83796089,  8.0760028 , 99.86189941],
       [21.09082644, 15.76734367, 53.25553826, 36.15973417, 35.97934941]])

#### 통계 함수
 - 평균, 분산, 중앙, 최대, 최소값 등등 통계 관련된 함수가 내장

In [7]:
print(y)

[[0.26852377 0.03421536 0.19640268 0.19258763 0.60889831]
 [0.8528341  0.73470471 0.37159011 0.99058906 0.09012446]
 [0.47413979 0.69764446 0.22532868 0.35951592 0.38911209]]


In [8]:
np.mean(y)

0.4324140751941965

In [9]:
y.mean()

0.4324140751941965

In [10]:
np.max(y)

0.9905890569122866

In [11]:
np.argmax(y)

8

In [12]:
np.var(y), np.median(y), np.std(y)

(0.07683349699572767, 0.37159011215338866, 0.27718855855847957)

#### 집계함수
 - 합계(sum), 누적합계(cumsum) 등등 계산 가능

In [13]:
y

array([[0.26852377, 0.03421536, 0.19640268, 0.19258763, 0.60889831],
       [0.8528341 , 0.73470471, 0.37159011, 0.99058906, 0.09012446],
       [0.47413979, 0.69764446, 0.22532868, 0.35951592, 0.38911209]])

In [15]:
np.sum(y)

6.486211127912948

In [16]:
np.sum(y, axis=0)

array([1.59549766, 1.46656453, 0.79332147, 1.5426926 , 1.08813486])

In [17]:
np.sum(y, axis=1)

array([1.30062775, 3.03984244, 2.14574094])

In [18]:
np.cumsum(y)

array([0.26852377, 0.30273913, 0.49914182, 0.69172945, 1.30062775,
       2.15346185, 2.88816656, 3.25975667, 4.25034573, 4.34047019,
       4.81460998, 5.51225444, 5.73758312, 6.09709903, 6.48621113])

#### any, all 함수
 - any: 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
 - all: 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [19]:
z = np.random.randn(10)
print(z)

[ 1.34072536 -0.48766506  0.66308105 -0.48055106  1.02622624 -1.68150648
 -0.8640761  -1.46313825 -0.57926439 -1.03266346]


In [20]:
z > 0

array([ True, False,  True, False,  True, False, False, False, False,
       False])

In [21]:
np.any(z > 0)

True

In [23]:
np.all(z > 0)

False

In [22]:
np.all(z != 0)

True

#### where 함수
 - 조건에 따라 선별적으로 값을 선택 가능
 - 사용 예) 음수인경우는 0, 나머지는 그대로 값을 쓰는 경우

In [24]:
z = np.random.randn(10)
print(z)

[-0.12250363 -0.1735027  -0.70076911 -0.27769762 -0.52523284  0.9094433
  1.73105241  0.79604073  2.04892931  0.61225861]


In [25]:
np.where(z > 0, z, 0)

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.9094433 , 1.73105241, 0.79604073, 2.04892931, 0.61225861])