### 학습목표
#### random 서브모듈 함수를 통해 ndarray 생성하기

In [1]:
import numpy as np

#### random 서브모듈

#### rand 함수
 - 0, 1사이의 분포로 랜덤한 ndarray 생성

In [3]:
np.random.rand(2, 4, 3)

array([[[0.45402595, 0.34832027, 0.76745745],
        [0.85612963, 0.15584692, 0.69565489],
        [0.14472472, 0.39288992, 0.8634677 ],
        [0.57237196, 0.43979542, 0.54209138]],

       [[0.81493802, 0.4324976 , 0.02120136],
        [0.233071  , 0.77059357, 0.27851236],
        [0.10225332, 0.78599685, 0.51112525],
        [0.02013065, 0.69923495, 0.225098  ]]])

#### randn함수
 - n: normal distribution(정규분포)
 - 정규분포로 샘플링된 랜덤 ndarray 생성

In [4]:
np.random.randn(5)

array([-0.28207818, -1.4230937 , -0.2111246 ,  0.07617425, -0.26637017])

In [5]:
np.random.randn(3, 4, 2)

array([[[-0.63779739,  1.23122288],
        [-1.90009175, -0.14678799],
        [ 1.83152374,  1.41037059],
        [ 0.41856384, -1.23489375]],

       [[-0.01463681,  2.02562307],
        [ 0.39853134,  0.16569868],
        [-0.20512895, -0.12457934],
        [-0.89280659,  0.66409851]],

       [[-0.53880181,  0.11988559],
        [ 3.18088303,  0.57823027],
        [-0.73977701, -0.40619944],
        [-0.97719888,  0.25543865]]])

#### randint 함수
 - 특정 정수 사이에서 랜덤하게 샘플링

In [6]:
np.random.randint(1, 100, size=(5,))

array([41,  8, 74, 39, 21])

In [7]:
np.random.randint(1, 100, size=(2,2))

array([[89, 70],
       [20, 78]])

#### seed 함수
 - 랜덤한 값을 동일하게 다시 생성하고자 할때 사용

In [9]:
np.random.seed(23)
np.random.randn(3, 4)

array([[ 0.66698806,  0.02581308, -0.77761941,  0.94863382],
       [ 0.70167179, -1.05108156, -0.36754812, -1.13745969],
       [-1.32214752,  1.77225828, -0.34745899,  0.67014016]])

#### choice
 - 주어진 1차원 ndarray로 부터 랜덤으로 샘플링
 - 정수가 주어진 경우, np.arange(해당숫자)로 간주

In [10]:
np.random.choice(100, size=(3, 4))

array([[79, 90, 62, 57],
       [19, 33, 59, 39],
       [15, 36, 65,  1]])

In [11]:
x = np.array([1, 2, 3, 1.5, 2.6, 4.9])
np.random.choice(x, size=(2, 2), replace=False)

array([[1. , 2. ],
       [3. , 4.9]])

In [13]:
x = np.array([1, 2, 3, 1.5, 2.6, 4.9])
np.random.choice(x, size=(2, 2))

array([[3. , 3. ],
       [2.6, 4.9]])

#### 확률분포에 따른 ndarray 생성
 - uniform
 - normal 등등

In [14]:
np.random.uniform(1.0, 3.0, size=(4, 5))

array([[1.69297888, 2.73957017, 1.85720362, 2.65750297, 2.43570368],
       [1.23845339, 2.19276835, 1.2595126 , 1.15506818, 2.66241051],
       [1.92877123, 1.32402496, 2.09595058, 2.17697164, 2.54722634],
       [2.31169092, 2.11541352, 1.35649453, 1.48116706, 2.01210926]])

In [16]:
np.random.normal(size=(3, 4))

array([[-0.7844428 , -0.22298831,  0.09849954, -1.06890465],
       [ 1.76858449,  3.65457335,  0.28665827, -0.36745524],
       [ 1.4486987 ,  0.53982103, -0.78814329, -0.07526169]])

In [17]:
np.random.randn(3, 4)

array([[-1.26734349,  2.01685756,  0.99023646, -0.21271875],
       [ 1.94332234, -0.90734715, -1.52441913,  0.40102559],
       [ 0.08508462, -1.0830194 , -0.94835843,  0.39442501]])