### 학습목표
#### boolean indexing의 이해

#### Boolean indexing
  - ndarry 인덱싱 시, bool 리스트를 전달하여 True인 경우만 필터링

* 브로드캐스팅을 활용하여 ndarray로 부터 bool list 얻기
 - 예) 짝수인 경우만 찾아보기

In [1]:
import numpy as np

In [2]:
x = np.random.randint(1, 100, size=10)
print(x)

[17 46 65 16 43 84 47 48  9 23]


In [3]:
even_mask = x % 2 == 0
print(even_mask)

[False  True False  True False  True False  True False False]


- bool 리스트를 인덱스로 전달

In [4]:
x[even_mask]

array([46, 16, 84, 48])

In [5]:
x[x % 2 == 0]

array([46, 16, 84, 48])

In [6]:
x[x > 50]

array([65, 84])

####  다중조건 사용하기
 - 파이썬 논리 연산지인 and, or, not 키워드 사용 불가
 - & - AND 
 - | - OR 

In [7]:
x % 2 == 0
x < 30

x[(x % 2 == 0) & (x < 30)]

array([16])

In [8]:
x < 30
x > 50

x[(x < 30) | (x > 50)]

array([17, 65, 16, 84,  9, 23])

#### 예제) 2019년 7월 서울 평균기온 데이터
 - 평균기온이 25도를 넘는 날수는?
 - 평균기온이 25를 넘는 날의 평균 기온은?

In [9]:
temp = np.array(
        [23.9, 24.4, 24.1, 25.4, 27.6, 29.7,
         26.7, 25.1, 25.0, 22.7, 21.9, 23.6, 
         24.9, 25.9, 23.8, 24.7, 25.6, 26.9, 
         28.6, 28.0, 25.1, 26.7, 28.1, 26.5, 
         26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])

 - 평균기온이 25도를 넘는 날수는?
 
 평균 기온이 25도를 넘는 날 필터링 후, len으로 날 수 counting

In [15]:
temp[temp > 25.0]

array([25.4, 27.6, 29.7, 26.7, 25.1, 25.9, 25.6, 26.9, 28.6, 28. , 25.1,
       26.7, 28.1, 26.5, 26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])

In [16]:
len(temp[temp > 25.0])

21

- 평균기온이 25를 넘는 날의 평균 기온은?

위에서 필터링 한 것에서 mean 함수를 호출

In [17]:
temp[temp > 25.0].mean()

## np.mean(temp[temp > 25.0]) 도 가능

26.857142857142858